### ISSUE TITLE
Example is not publicly available

### ISSUE THREAD

**Issue by Pascal-Orthopy** [iits-consulting/charts#3]
Hi,

we tried to update our ArgoCD Helm Chart and now our infrastructure chart is not working.
The mentioned example Helm Chart is not publicly available: https://github.com/victorgetz/infrastructure-charts
It would be nice if the code is also available to check what we missed.

* https://github.com/iits-consulting/charts/tree/main/charts/argocd
* https://github.com/victorgetz/infrastructure-charts

**Comment by Pascal-Orthopy** [comment]
Could it be that the variables changed from "globals" to "projectValues" and that the old templates not working with the changes: https://github.com/iits-consulting/otc-infrastructure-charts-template/tree/main/stages/dev/templates

**Comment by victorgetz** [comment]
You guys are fast :1st_place_medal: 

I still working on the new structure that's why i did not make it public yet.

Yes it consists of major breaking changes. I am sorry for that.

**Comment by victorgetz** [comment]
https://github.com/iits-consulting/otc-infrastructure-charts-template is updated now
