### ISSUE TITLE
iits-admin-dashboard cannot handle PathPrefix on non-root paths

### ISSUE THREAD

**Issue by krankkkk** [iits-consulting/charts#79]
If you set the `ingressRoute.pathPrefix` to something that is not `"/"` you will only get an 404 as the underlying image can only handle request for the root `"/"` 

I.e. set  `ingressRoute.pathPrefix` to `/admin` and you will get a 404

So either tell the underlying image to always send the index.html (Might be a problem for local images/css)
Or add a `strip-prefix` middleware so the request will be answered correctly (Might also need to add the pathPrefix to image/css paths then)

**Comment by victorgetz** [comment]
Should be fixed pls try again
